import type { Metadata } from "next";
import "./globals.css";
import { fonts } from "@/lib/fonts";
import { Providers } from "@/app/providers";

export const metadata: Metadata = {
	title: "Tiny Links",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={fonts.inter.variable}>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
